# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NViJRr5uKCRKC2dV5FVB-Qp4Cgtvj1wa
"""

import numpy as np
import matplotlib.pyplot as plt

def lag(xp,yp,x):
    r=0
    for i in range(len(xp)):
        L=1
        for j in range(len(xp)):
            if i!=j:
                L=L*(x-xp[j])/(xp[i]-xp[j])
        r=r+yp[i]*L
    return r

def nc(xp,yp):
    c=yp.copy()
    n=len(xp)
    for j in range(1,n):
        for i in range(n-1,j-1,-1):
            c[i]=(c[i]-c[i-1])/(xp[i]-xp[i-j])
    return c

def new(xp,yp,x):
    c=nc(xp,yp)
    r=c[-1]
    for i in range(len(xp)-2,-1,-1):
        r=r*(x-xp[i])+c[i]
    return r

def lb(xp,k,x):
    r=1
    for j in range(len(xp)):
        if j!=k:
            r=r*(x-xp[j])/(xp[k]-xp[j])
    return r

def dlb(xp,k):
    r=0
    for j in range(len(xp)):
        if j!=k:
            r=r+1/(xp[k]-xp[j])
    return r

def her(xp,f,df,x):
    r=0
    for k in range(len(xp)):
        lk=lb(xp,k,x)
        dlk=dlb(xp,k)
        hk=(1-2*(x-xp[k])*dlk)*lk**2
        hh=(x-xp[k])*lk**2
        r=r+f(xp[k])*hk
        r=r+df(xp[k])*hh
    return r

fs=[
    ("exp(x)",lambda x:np.exp(x),lambda x:np.exp(x),0,2),
    ("sin(x)",lambda x:np.sin(x),lambda x:np.cos(x),0,2*np.pi)
]

for name,f,df,a,b in fs:
    x=np.linspace(a,b,500)

    for n in [3,5,7]:
        xp=np.linspace(a,b,n)
        yp=f(xp)

        yl=[]
        yn=[]
        yh=[]

        for xi in x:
            yl.append(lag(xp,yp,xi))
            yn.append(new(xp,yp,xi))
            yh.append(her(xp,f,df,xi))

        yl=np.array(yl)
        yn=np.array(yn)
        yh=np.array(yh)

        el=np.max(np.abs(f(x)-yl))
        en=np.max(np.abs(f(x)-yn))
        eh=np.max(np.abs(f(x)-yh))

        print("\nFunction:",name)
        print("Number of points:",n)
        print("Lagrange error:",el)
        print("Newton error:",en)
        print("Hermite error:",eh)

        plt.figure(figsize=(8,5))
        plt.plot(x,f(x),label="Original")
        plt.plot(x,yl,"--",label="Lagrange")
        plt.plot(x,yn,":",label="Newton")
        plt.plot(x,yh,"-.",label="Hermite")
        plt.scatter(xp,yp,label="Points")

        plt.title(name+" interpolation with "+str(n)+" points")
        plt.xlabel("x")
        plt.ylabel("f(x)")
        plt.legend()
        plt.grid()
        plt.show()